version: "3.9"
services:
  auth_db:
    image: "postgres:14.4"
    restart: always
    container_name: "auth_postgres"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54322:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=auth_db
      - DB_PORT=5432   
    container_name: "opub_auth_server"
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - auth_db
volumes:
  auth_postgres_data:
    name: auth_postgres_data
