version: "3.9"
services:
  auth_db:
    image: "postgres:14.4"
    restart: always
    container_name: "auth_postgres"
    ports:
      - "54322:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
  web:
    build: .  
    container_name: "opub_auth_server"
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - auth_db
volumes:
  auth_postgres_data:
    name: auth_postgres_data
